/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grill;

/**
 *
 * @author Jack
 */
public class grill extends javax.swing.JFrame 
{

    /**
     * Creates new form grill
     */
    public grill() 
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel00_00 = new javax.swing.JLabel();
        jLabel01_00 = new javax.swing.JLabel();
        jLabel02_00 = new javax.swing.JLabel();
        jLabel03_00 = new javax.swing.JLabel();
        jLabel04_00 = new javax.swing.JLabel();
        jLabel05_00 = new javax.swing.JLabel();
        jLabel06_00 = new javax.swing.JLabel();
        jLabel07_00 = new javax.swing.JLabel();
        jLabel08_00 = new javax.swing.JLabel();
        jLabel09_00 = new javax.swing.JLabel();
        jLabel10_00 = new javax.swing.JLabel();
        jLabel11_00 = new javax.swing.JLabel();
        jLabel12_00 = new javax.swing.JLabel();
        jLabel13_00 = new javax.swing.JLabel();
        jLabel14_00 = new javax.swing.JLabel();
        jLabel15_00 = new javax.swing.JLabel();
        jLabel16_00 = new javax.swing.JLabel();
        jLabel17_00 = new javax.swing.JLabel();
        jLabel18_00 = new javax.swing.JLabel();
        jLabel19_00 = new javax.swing.JLabel();
        jLabel20_00 = new javax.swing.JLabel();
        jLabel21_00 = new javax.swing.JLabel();
        jLabel22_00 = new javax.swing.JLabel();
        jLabel23_00 = new javax.swing.JLabel();
        jLabel24_00 = new javax.swing.JLabel();
        jLabel25_00 = new javax.swing.JLabel();
        jLabel26_00 = new javax.swing.JLabel();
        jLabel27_00 = new javax.swing.JLabel();
        jLabel28_00 = new javax.swing.JLabel();
        jLabel29_00 = new javax.swing.JLabel();
        jLabel30_00 = new javax.swing.JLabel();
        jLabel31_00 = new javax.swing.JLabel();
        jLabel00_01 = new javax.swing.JLabel();
        jLabel00_02 = new javax.swing.JLabel();
        jLabel00_03 = new javax.swing.JLabel();
        jLabel00_04 = new javax.swing.JLabel();
        jLabel00_05 = new javax.swing.JLabel();
        jLabel00_06 = new javax.swing.JLabel();
        jLabel00_07 = new javax.swing.JLabel();
        jLabel00_08 = new javax.swing.JLabel();
        jLabel00_09 = new javax.swing.JLabel();
        jLabel00_10 = new javax.swing.JLabel();
        jLabel00_11 = new javax.swing.JLabel();
        jLabel00_12 = new javax.swing.JLabel();
        jLabel00_13 = new javax.swing.JLabel();
        jLabel00_14 = new javax.swing.JLabel();
        jLabel00_15 = new javax.swing.JLabel();
        jLabel00_16 = new javax.swing.JLabel();
        jLabel00_17 = new javax.swing.JLabel();
        jLabel00_18 = new javax.swing.JLabel();
        jLabel00_19 = new javax.swing.JLabel();
        jLabel00_20 = new javax.swing.JLabel();
        jLabel00_21 = new javax.swing.JLabel();
        jLabel00_22 = new javax.swing.JLabel();
        jLabel00_23 = new javax.swing.JLabel();
        jLabel00_24 = new javax.swing.JLabel();
        jLabel00_25 = new javax.swing.JLabel();
        jLabel00_26 = new javax.swing.JLabel();
        jLabel00_27 = new javax.swing.JLabel();
        jLabel00_28 = new javax.swing.JLabel();
        jLabel00_29 = new javax.swing.JLabel();
        jLabel00_30 = new javax.swing.JLabel();
        jLabel00_31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1024, 1024));
        setMinimumSize(new java.awt.Dimension(1024, 1024));
        setPreferredSize(new java.awt.Dimension(1024, 1024));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel00_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_00.setText("0,0");
        jLabel00_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel00_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel00_00.setName("0,0"); // NOI18N
        jLabel00_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_00, gridBagConstraints);

        jLabel01_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel01_00.setText("1,0");
        jLabel01_00.setToolTipText("");
        jLabel01_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel01_00.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel01_00.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel01_00.setName("1,0"); // NOI18N
        jLabel01_00.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel01_00, gridBagConstraints);

        jLabel02_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel02_00.setText("2,0");
        jLabel02_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel02_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel02_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel02_00.setName("2,0"); // NOI18N
        jLabel02_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel02_00, gridBagConstraints);

        jLabel03_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel03_00.setText("3,0");
        jLabel03_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel03_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel03_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel03_00.setName("3,0"); // NOI18N
        jLabel03_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel03_00, gridBagConstraints);

        jLabel04_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel04_00.setText("4,0");
        jLabel04_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel04_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel04_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel04_00.setName("4,0"); // NOI18N
        jLabel04_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel04_00, gridBagConstraints);

        jLabel05_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel05_00.setText("5,0");
        jLabel05_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel05_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel05_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel05_00.setName("5,0"); // NOI18N
        jLabel05_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel05_00, gridBagConstraints);

        jLabel06_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel06_00.setText("6,0");
        jLabel06_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel06_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel06_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel06_00.setName("6,0"); // NOI18N
        jLabel06_00.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel06_00.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        getContentPane().add(jLabel06_00, gridBagConstraints);

        jLabel07_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel07_00.setText("7,0");
        jLabel07_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel07_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel07_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel07_00.setName("7,0"); // NOI18N
        jLabel07_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        getContentPane().add(jLabel07_00, gridBagConstraints);

        jLabel08_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel08_00.setText("8,0");
        jLabel08_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel08_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel08_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel08_00.setName("8,0"); // NOI18N
        jLabel08_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jLabel08_00, gridBagConstraints);

        jLabel09_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel09_00.setText("9,0");
        jLabel09_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel09_00.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel09_00.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel09_00.setName("9,0"); // NOI18N
        jLabel09_00.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        getContentPane().add(jLabel09_00, gridBagConstraints);

        jLabel10_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10_00.setText("10,0");
        jLabel10_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel10_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel10_00.setName("10,0"); // NOI18N
        jLabel10_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        getContentPane().add(jLabel10_00, gridBagConstraints);

        jLabel11_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11_00.setText("11,0");
        jLabel11_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel11_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel11_00.setName("11,0"); // NOI18N
        jLabel11_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        getContentPane().add(jLabel11_00, gridBagConstraints);

        jLabel12_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12_00.setText("12,0");
        jLabel12_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel12_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel12_00.setName("12,0"); // NOI18N
        jLabel12_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        getContentPane().add(jLabel12_00, gridBagConstraints);

        jLabel13_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13_00.setText("13,0");
        jLabel13_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel13_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel13_00.setName("13,0"); // NOI18N
        jLabel13_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        getContentPane().add(jLabel13_00, gridBagConstraints);

        jLabel14_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14_00.setText("14,0");
        jLabel14_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14_00.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel14_00.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel14_00.setName("14,0"); // NOI18N
        jLabel14_00.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jLabel14_00, gridBagConstraints);

        jLabel15_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15_00.setText("15,0");
        jLabel15_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel15_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel15_00.setName("15,0"); // NOI18N
        jLabel15_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        getContentPane().add(jLabel15_00, gridBagConstraints);

        jLabel16_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16_00.setText("16,0");
        jLabel16_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel16_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel16_00.setName("16,0"); // NOI18N
        jLabel16_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        getContentPane().add(jLabel16_00, gridBagConstraints);

        jLabel17_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17_00.setText("17,0");
        jLabel17_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel17_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel17_00.setName("17,0"); // NOI18N
        jLabel17_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        getContentPane().add(jLabel17_00, gridBagConstraints);

        jLabel18_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18_00.setText("18,0");
        jLabel18_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel18_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel18_00.setName("18,0"); // NOI18N
        jLabel18_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        getContentPane().add(jLabel18_00, gridBagConstraints);

        jLabel19_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19_00.setText("19,0");
        jLabel19_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel19_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel19_00.setName("19,0"); // NOI18N
        jLabel19_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        getContentPane().add(jLabel19_00, gridBagConstraints);

        jLabel20_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20_00.setText("20,0");
        jLabel20_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20_00.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel20_00.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel20_00.setName("20,0"); // NOI18N
        jLabel20_00.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel20_00, gridBagConstraints);

        jLabel21_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21_00.setText("21,0");
        jLabel21_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel21_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel21_00.setName("21,0"); // NOI18N
        jLabel21_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        getContentPane().add(jLabel21_00, gridBagConstraints);

        jLabel22_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22_00.setText("22,0");
        jLabel22_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel22_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel22_00.setName("22,0"); // NOI18N
        jLabel22_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        getContentPane().add(jLabel22_00, gridBagConstraints);

        jLabel23_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23_00.setText("23,0");
        jLabel23_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel23_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel23_00.setName("23,0"); // NOI18N
        jLabel23_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        getContentPane().add(jLabel23_00, gridBagConstraints);

        jLabel24_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_00.setText("24,0");
        jLabel24_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24_00.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel24_00.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel24_00.setName("24,0"); // NOI18N
        jLabel24_00.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        getContentPane().add(jLabel24_00, gridBagConstraints);

        jLabel25_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25_00.setText("25,0");
        jLabel25_00.setToolTipText("");
        jLabel25_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel25_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel25_00.setName("25,0"); // NOI18N
        jLabel25_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        getContentPane().add(jLabel25_00, gridBagConstraints);

        jLabel26_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26_00.setText("26,0");
        jLabel26_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel26_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel26_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel26_00.setName("26,0"); // NOI18N
        jLabel26_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        getContentPane().add(jLabel26_00, gridBagConstraints);

        jLabel27_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27_00.setText("27,0");
        jLabel27_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel27_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel27_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel27_00.setName("27,0"); // NOI18N
        jLabel27_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        getContentPane().add(jLabel27_00, gridBagConstraints);

        jLabel28_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28_00.setText("28,0");
        jLabel28_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel28_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel28_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel28_00.setName("28,0"); // NOI18N
        jLabel28_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        getContentPane().add(jLabel28_00, gridBagConstraints);

        jLabel29_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29_00.setText("29,0");
        jLabel29_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel29_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel29_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel29_00.setName("29,0"); // NOI18N
        jLabel29_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 29;
        getContentPane().add(jLabel29_00, gridBagConstraints);

        jLabel30_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30_00.setText("30,0");
        jLabel30_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel30_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel30_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel30_00.setName("30,0"); // NOI18N
        jLabel30_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        getContentPane().add(jLabel30_00, gridBagConstraints);

        jLabel31_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31_00.setText("31,0");
        jLabel31_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel31_00.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel31_00.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel31_00.setName("31,0"); // NOI18N
        jLabel31_00.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 31;
        getContentPane().add(jLabel31_00, gridBagConstraints);

        jLabel00_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_01.setText("0,1");
        jLabel00_01.setToolTipText("");
        jLabel00_01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_01.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel00_01.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel00_01.setName("0,1"); // NOI18N
        jLabel00_01.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_01, gridBagConstraints);

        jLabel00_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_02.setText("0,2");
        jLabel00_02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_02.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_02.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_02.setName("0,2"); // NOI18N
        jLabel00_02.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_02, gridBagConstraints);

        jLabel00_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_03.setText("0,3");
        jLabel00_03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_03.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_03.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_03.setName("3,0"); // NOI18N
        jLabel00_03.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_03, gridBagConstraints);

        jLabel00_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_04.setText("0,4");
        jLabel00_04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_04.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_04.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_04.setName("0,4"); // NOI18N
        jLabel00_04.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_04, gridBagConstraints);

        jLabel00_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_05.setText("0,5");
        jLabel00_05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_05.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_05.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_05.setName("0,5"); // NOI18N
        jLabel00_05.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_05, gridBagConstraints);

        jLabel00_06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_06.setText("0,6");
        jLabel00_06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_06.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_06.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_06.setName("0,6"); // NOI18N
        jLabel00_06.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_06, gridBagConstraints);

        jLabel00_07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_07.setText("0,7");
        jLabel00_07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_07.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_07.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_07.setName("0,7"); // NOI18N
        jLabel00_07.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_07, gridBagConstraints);

        jLabel00_08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_08.setText("0,8");
        jLabel00_08.setToolTipText("");
        jLabel00_08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_08.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_08.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_08.setName("0,8"); // NOI18N
        jLabel00_08.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_08, gridBagConstraints);

        jLabel00_09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_09.setText("0,9");
        jLabel00_09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_09.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_09.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_09.setName("0,9"); // NOI18N
        jLabel00_09.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_09, gridBagConstraints);

        jLabel00_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_10.setText("0,10");
        jLabel00_10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_10.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_10.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_10.setName("0,10"); // NOI18N
        jLabel00_10.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_10, gridBagConstraints);

        jLabel00_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_11.setText("0,11");
        jLabel00_11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_11.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_11.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_11.setName("0,11"); // NOI18N
        jLabel00_11.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_11, gridBagConstraints);

        jLabel00_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_12.setText("0,12");
        jLabel00_12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_12.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_12.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_12.setName("0,12"); // NOI18N
        jLabel00_12.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_12, gridBagConstraints);

        jLabel00_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_13.setText("0,13");
        jLabel00_13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_13.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_13.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_13.setName("0,13"); // NOI18N
        jLabel00_13.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_13, gridBagConstraints);

        jLabel00_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_14.setText("0,14");
        jLabel00_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_14.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_14.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_14.setName("0,14"); // NOI18N
        jLabel00_14.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_14, gridBagConstraints);

        jLabel00_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_15.setText("0,15");
        jLabel00_15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_15.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_15.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_15.setName("0,15"); // NOI18N
        jLabel00_15.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_15, gridBagConstraints);

        jLabel00_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_16.setText("0,16");
        jLabel00_16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_16.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_16.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_16.setName("0,16"); // NOI18N
        jLabel00_16.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_16, gridBagConstraints);

        jLabel00_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_17.setText("0,17");
        jLabel00_17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_17.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_17.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_17.setName("0,17"); // NOI18N
        jLabel00_17.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_17, gridBagConstraints);

        jLabel00_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_18.setText("0,18");
        jLabel00_18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_18.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_18.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_18.setName("0,18"); // NOI18N
        jLabel00_18.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_18, gridBagConstraints);

        jLabel00_19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_19.setText("0,19");
        jLabel00_19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_19.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_19.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_19.setName("0,19"); // NOI18N
        jLabel00_19.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_19, gridBagConstraints);

        jLabel00_20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_20.setText("0,20");
        jLabel00_20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_20.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_20.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_20.setName("0,20"); // NOI18N
        jLabel00_20.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_20, gridBagConstraints);

        jLabel00_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_21.setText("0,21");
        jLabel00_21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_21.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_21.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_21.setName("0,21"); // NOI18N
        jLabel00_21.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_21, gridBagConstraints);

        jLabel00_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_22.setText("0,22");
        jLabel00_22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_22.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_22.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_22.setName("0,22"); // NOI18N
        jLabel00_22.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_22, gridBagConstraints);

        jLabel00_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_23.setText("0,23");
        jLabel00_23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_23.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_23.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_23.setName("0,23"); // NOI18N
        jLabel00_23.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_23, gridBagConstraints);

        jLabel00_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_24.setText("0,24");
        jLabel00_24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_24.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_24.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_24.setName("0,24"); // NOI18N
        jLabel00_24.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_24, gridBagConstraints);

        jLabel00_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_25.setText("0,25");
        jLabel00_25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_25.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_25.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_25.setName("0,25"); // NOI18N
        jLabel00_25.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 25;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_25, gridBagConstraints);

        jLabel00_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_26.setText("0,26");
        jLabel00_26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_26.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_26.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_26.setName("0,26"); // NOI18N
        jLabel00_26.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_26, gridBagConstraints);

        jLabel00_27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_27.setText("0,27");
        jLabel00_27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_27.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_27.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_27.setName("0,27"); // NOI18N
        jLabel00_27.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 27;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_27, gridBagConstraints);

        jLabel00_28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_28.setText("0,28");
        jLabel00_28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_28.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_28.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_28.setName("0,28"); // NOI18N
        jLabel00_28.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_28, gridBagConstraints);

        jLabel00_29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_29.setText("0,29");
        jLabel00_29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_29.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_29.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_29.setName("0,29"); // NOI18N
        jLabel00_29.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_29, gridBagConstraints);

        jLabel00_30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_30.setText("0,30");
        jLabel00_30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_30.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_30.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_30.setName("0,30"); // NOI18N
        jLabel00_30.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_30, gridBagConstraints);

        jLabel00_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00_31.setText("0,31");
        jLabel00_31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel00_31.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel00_31.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel00_31.setName("0,31"); // NOI18N
        jLabel00_31.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel00_31, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("O:\\NetBeans\\grill\\diagonal.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel2.setMaximumSize(new java.awt.Dimension(160, 160));
        jLabel2.setMinimumSize(new java.awt.Dimension(160, 160));
        jLabel2.setName("v1"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(160, 160));
        getContentPane().add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setText("Gm7");
        getContentPane().add(jLabel3, new java.awt.GridBagConstraints());

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(105, 105));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(105, 105));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(105, 105));
        jLayeredPane1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon("O:\\NetBeans\\grill\\diagonal.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jLayeredPane1.add(jLabel4, gridBagConstraints);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(jLayeredPane1, gridBagConstraints);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("jLabel5");
        jLayeredPane2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 29, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 255, 255));
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("jLabel6");
        jLayeredPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 36, -1, -1));

        getContentPane().add(jLayeredPane2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new grill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel00_00;
    private javax.swing.JLabel jLabel00_01;
    private javax.swing.JLabel jLabel00_02;
    private javax.swing.JLabel jLabel00_03;
    private javax.swing.JLabel jLabel00_04;
    private javax.swing.JLabel jLabel00_05;
    private javax.swing.JLabel jLabel00_06;
    private javax.swing.JLabel jLabel00_07;
    private javax.swing.JLabel jLabel00_08;
    private javax.swing.JLabel jLabel00_09;
    private javax.swing.JLabel jLabel00_10;
    private javax.swing.JLabel jLabel00_11;
    private javax.swing.JLabel jLabel00_12;
    private javax.swing.JLabel jLabel00_13;
    private javax.swing.JLabel jLabel00_14;
    private javax.swing.JLabel jLabel00_15;
    private javax.swing.JLabel jLabel00_16;
    private javax.swing.JLabel jLabel00_17;
    private javax.swing.JLabel jLabel00_18;
    private javax.swing.JLabel jLabel00_19;
    private javax.swing.JLabel jLabel00_20;
    private javax.swing.JLabel jLabel00_21;
    private javax.swing.JLabel jLabel00_22;
    private javax.swing.JLabel jLabel00_23;
    private javax.swing.JLabel jLabel00_24;
    private javax.swing.JLabel jLabel00_25;
    private javax.swing.JLabel jLabel00_26;
    private javax.swing.JLabel jLabel00_27;
    private javax.swing.JLabel jLabel00_28;
    private javax.swing.JLabel jLabel00_29;
    private javax.swing.JLabel jLabel00_30;
    private javax.swing.JLabel jLabel00_31;
    private javax.swing.JLabel jLabel01_00;
    private javax.swing.JLabel jLabel02_00;
    private javax.swing.JLabel jLabel03_00;
    private javax.swing.JLabel jLabel04_00;
    private javax.swing.JLabel jLabel05_00;
    private javax.swing.JLabel jLabel06_00;
    private javax.swing.JLabel jLabel07_00;
    private javax.swing.JLabel jLabel08_00;
    private javax.swing.JLabel jLabel09_00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_00;
    private javax.swing.JLabel jLabel11_00;
    private javax.swing.JLabel jLabel12_00;
    private javax.swing.JLabel jLabel13_00;
    private javax.swing.JLabel jLabel14_00;
    private javax.swing.JLabel jLabel15_00;
    private javax.swing.JLabel jLabel16_00;
    private javax.swing.JLabel jLabel17_00;
    private javax.swing.JLabel jLabel18_00;
    private javax.swing.JLabel jLabel19_00;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20_00;
    private javax.swing.JLabel jLabel21_00;
    private javax.swing.JLabel jLabel22_00;
    private javax.swing.JLabel jLabel23_00;
    private javax.swing.JLabel jLabel24_00;
    private javax.swing.JLabel jLabel25_00;
    private javax.swing.JLabel jLabel26_00;
    private javax.swing.JLabel jLabel27_00;
    private javax.swing.JLabel jLabel28_00;
    private javax.swing.JLabel jLabel29_00;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30_00;
    private javax.swing.JLabel jLabel31_00;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel chordGrid[][];
   

}
